apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  labels:
    app: weather-api
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: weather-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api-container
          image: jdzaky/weather_api_dzaky:v1.0
          resources:
            requests:
              memory: "256Mi" 
              cpu: "250m"    
            limits:
              memory: "512Mi"
              cpu: "500m"  
          ports:
            - containerPort: 8080 
